### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by felipesanches** [graphicore/librebarcode#7]
I checked out the repo, followed the README instructions installing all dependencies on a virtualenv and then I got this:

```
(venv) felipe@guarana:~/devel/github_graphicore/librebarcode (master)*$ ./app/bin/buildAll
Got following parameters for Code39Builder:
  bottom: 0(default)
  example: 123
  fontBelowHeight: 390(default)
  force: false(default)
  narrow: 30(default)
  top: 590(default)
  wide: 90
  wideToNarrowRatio: 3(default)

ReferenceError: Set is not defined
    at Code39Glyph.Object.defineProperties.width.get [as width] (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/code39.js:105:37)
    at Code39Glyph.Object.defineProperties.glifData.get [as glifData] (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/code39.js:134:32)
    at Code39Builder._p.drawGlyphs (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/abstract.js:393:57)
    at Code39Builder._p.populateGlyphSet (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/abstract.js:408:14)
    at /home/felipe/devel/github_graphicore/librebarcode/app/lib/builder.js:57:17
    at Command.main (/home/felipe/devel/github_graphicore/librebarcode/app/bin/build:50:9)
    at Command.listener (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:293:8)
    at Command.emit (events.js:95:17)
    at Command.parseArgs (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:609:12)
    at Command.parse (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:452:21)
INFO:fontmake.font_project:Building TTFs
Traceback (most recent call last):
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 481, in run_from_ufos
    **kwargs)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 188, in build_ttfs
    self.decompose_glyphs(ufos, glyph_filter=lambda g: g)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 126, in decompose_glyphs
    logger.info('Decomposing glyphs for ' + self._font_name(ufo))
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 497, in _font_name
    return '%s-%s' % (ufo.info.familyName.replace(' ', ''),
AttributeError: 'NoneType' object has no attribute 'replace'

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/felipe/devel/github_graphicore/librebarcode/../fonts/ofl/inconsolata/Inconsolata-Regular.ttf'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at fontkit.openSync (/home/felipe/devel/github_graphicore/librebarcode/node_modules/fontkit/index.js:43:19)
    at Command.<anonymous> (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:387:35)
    at Command.emit (events.js:95:17)
    at Command.parseOptions (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:682:14)
    at Command.parse (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:449:21)
    at /home/felipe/devel/github_graphicore/librebarcode/app/bin/build:81:13
    at Object.context.execCb (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1946:33)
    at Object.Module.check (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1133:51)
Traceback (most recent call last):
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 468, in run_from_ufos
    ufos = [Font(path) for path in ufo_paths]
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/defcon/objects/font.py", line 137, in __init__
    reader = UFOReader(self._path)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/ufoLib/__init__.py", line 125, in __init__
    raise UFOLibError("The specified UFO doesn't exist.")
ufoLib.UFOLibError: The specified UFO doesn't exist.
Got following parameters for Code39ExtendedBuilder:
  bottom: 0(default)
  fontBelowHeight: 390(default)
  force: false(default)
  top: 590(default)

ReferenceError: Set is not defined
    at Code39Glyph.Object.defineProperties.width.get [as width] (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/code39.js:105:37)
    at Code39Glyph.Object.defineProperties.glifData.get [as glifData] (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/code39.js:134:32)
    at Code39Builder._p.drawGlyphs (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/abstract.js:393:57)
    at Code39ExtendedBuilder._p.populateGlyphSet (/home/felipe/devel/github_graphicore/librebarcode/app/lib/builder/code39Extended.js:213:28)
    at /home/felipe/devel/github_graphicore/librebarcode/app/lib/builder.js:57:17
    at Command.main (/home/felipe/devel/github_graphicore/librebarcode/app/bin/build:50:9)
    at Command.listener (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:293:8)
    at Command.emit (events.js:95:17)
    at Command.parseArgs (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:609:12)
    at Command.parse (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:452:21)
INFO:fontmake.font_project:Building TTFs
Traceback (most recent call last):
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 481, in run_from_ufos
    **kwargs)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 188, in build_ttfs
    self.decompose_glyphs(ufos, glyph_filter=lambda g: g)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 126, in decompose_glyphs
    logger.info('Decomposing glyphs for ' + self._font_name(ufo))
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 497, in _font_name
    return '%s-%s' % (ufo.info.familyName.replace(' ', ''),
AttributeError: 'NoneType' object has no attribute 'replace'

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/felipe/devel/github_graphicore/librebarcode/../fonts/ofl/inconsolata/Inconsolata-Regular.ttf'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at fontkit.openSync (/home/felipe/devel/github_graphicore/librebarcode/node_modules/fontkit/index.js:43:19)
    at Command.<anonymous> (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:387:35)
    at Command.emit (events.js:95:17)
    at Command.parseOptions (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:682:14)
    at Command.parse (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:449:21)
    at /home/felipe/devel/github_graphicore/librebarcode/app/bin/build:81:13
    at Object.context.execCb (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1946:33)
    at Object.Module.check (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1133:51)
Traceback (most recent call last):
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 468, in run_from_ufos
    ufos = [Font(path) for path in ufo_paths]
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/defcon/objects/font.py", line 137, in __init__
    reader = UFOReader(self._path)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/ufoLib/__init__.py", line 125, in __init__
    raise UFOLibError("The specified UFO doesn't exist.")
ufoLib.UFOLibError: The specified UFO doesn't exist.
Got following parameters for Code128Builder:
  bottom: 0(default)
  fontBelowHeight: 390(default)
  force: false(default)
  top: 590(default)
  unit: 30(default)
INFO:fontmake.font_project:Building TTFs
INFO:fontmake.font_project:Decomposing glyphs for LibreBarcode128-Regular
INFO:fontmake.font_project:Converting curves for LibreBarcode128-Regular
INFO:fontmake.font_project:Saving TTF for LibreBarcode128-Regular
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/felipe/devel/github_graphicore/librebarcode/../fonts/ofl/inconsolata/Inconsolata-Regular.ttf'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at fontkit.openSync (/home/felipe/devel/github_graphicore/librebarcode/node_modules/fontkit/index.js:43:19)
    at Command.<anonymous> (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:387:35)
    at Command.emit (events.js:95:17)
    at Command.parseOptions (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:682:14)
    at Command.parse (/home/felipe/devel/github_graphicore/librebarcode/node_modules/commander/index.js:449:21)
    at /home/felipe/devel/github_graphicore/librebarcode/app/bin/build:81:13
    at Object.context.execCb (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1946:33)
    at Object.Module.check (/home/felipe/devel/github_graphicore/librebarcode/node_modules/requirejs/bin/r.js:1133:51)
Traceback (most recent call last):
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/__main__.py", line 195, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/fontmake/font_project.py", line 468, in run_from_ufos
    ufos = [Font(path) for path in ufo_paths]
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/defcon/objects/font.py", line 137, in __init__
    reader = UFOReader(self._path)
  File "/home/felipe/devel/github_graphicore/librebarcode/venv/local/lib/python2.7/site-packages/ufoLib/__init__.py", line 125, in __init__
    raise UFOLibError("The specified UFO doesn't exist.")
ufoLib.UFOLibError: The specified UFO doesn't exist.
LibreBarcode128-Regular.ttf  OFL.txt
usage: fontbakery [-h] [--list-subcommands] subcommand
fontbakery: error: unrecognized arguments: --autofix fonts/LibreBarcode128-Regular.ttf
```

**Comment by graphicore** [comment]
`Set is not defined`

Looks like your nodejs is seriously old.

**Comment by graphicore** [comment]
can you reproduce this session:

```
$ node
> process.version
'v6.9.2'
> new Set()
Set {}
>
```

**Comment by felipesanches** [comment]
```
(venv) felipe@guarana:~/devel/github_graphicore/librebarcode (master)*$ node
> process.version
'v0.10.40'
> new Set()
ReferenceError: Set is not defined
    at repl:1:6
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
> 
```

ooops :-)

**Comment by graphicore** [comment]
I use this: https://github.com/creationix/nvm

but I'm not sure if it interferes with your system node install

**Comment by felipesanches** [comment]
well... I think I won't have to build it myself anymore since I already dealt with the binaries from google/fonts git repo to address this issue: https://github.com/googlefonts/fontbakery/issues/1534
